-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 22:39:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(30) NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Rol_idRol`),
  INDEX `fk_Usuario_Rol_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videoBeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videoBeams` (
  `idvideoBeams` INT NOT NULL,
  `serial` VARCHAR(200) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idvideoBeams`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AgendaVideoBeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AgendaVideoBeam` (
  `idAgendaVideoBeam` INT NULL,
  `fechaInicio` DATETIME NULL,
  `fechaFin` DATETIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Rol_idRol` INT NOT NULL,
  `videoBeams_idvideoBeams` INT NOT NULL,
  PRIMARY KEY (`idAgendaVideoBeam`),
  INDEX `fk_AgendaVideoBeam_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Rol_idRol` ASC) VISIBLE,
  INDEX `fk_AgendaVideoBeam_videoBeams1_idx` (`videoBeams_idvideoBeams` ASC) VISIBLE,
  CONSTRAINT `fk_AgendaVideoBeam_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Rol_idRol`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Rol_idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgendaVideoBeam_videoBeams1`
    FOREIGN KEY (`videoBeams_idvideoBeams`)
    REFERENCES `mydb`.`videoBeams` (`idvideoBeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
